### ISSUE TITLE
Add persist form functionality 

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/reactive-forms#24]
It'll be great to add a built-in method to persist the form value to the storage. For example:

```ts
const profileForm = new FormGroup<Profile>({
  firstName: new FormControl(''),
  lastName: new FormControl(''),
  skills: new FormArray([]),
  address: new FormGroup({
    street: new FormControl(''),
    city: new FormControl('')
  })
});

profileForm.persist(key, storage);
```

Where the `key` is the storage key, and the storage is `local` or `session`.

**Comment by caroso1222** [comment]
I wonder if you'd like to follow a more functional approach for the API on this one. Something along the lines of

```typescript
import { LocalStorageManager } from '@ngneat/reactive-forms';

const profileForm = new FormGroup<Profile>({
  firstName: new FormControl(''),
  lastName: new FormControl(''),
});

LocalStorageManager.serialize(key, profileForm)
LocalStorageManager.deserialize(key)
```

It would allow the feature to scale with more managers like `SessionStorageManager`, `IndexedDBManager`, all of them implementing a common `IPersistManager` interface.

Not sure about this claim, but I suppose this could be easier to tree shake rather than having a `persist` method with a switch-case statement for `local`, `session`, etc.

I don't have any problem with `.persist`, though. Just picking brains on this one.

**Comment by NetanelBasal** [comment]
We can combine the ideas and create something like:

`profileForm.persist(key: string, storage: IPersistManager)`

I think we still need to provide at least the default behavior and save it to `localstorage` if `storage` isn't provided.
